### ISSUE TITLE
the docker image shows some problem when using it in disconnect internet

### ISSUE THREAD

**Issue by wangfeng-skymind** [SkymindIO/SKIL-CE#48]
![1111173826](https://user-images.githubusercontent.com/29109492/44142310-6a702bc6-a0b2-11e8-8011-c95e15f922a2.png)
09:21:09.087 [application-akka.actor.default-dispatcher-22] ERROR p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.routing.RouterBuilderHelper$$anonfun$build$1$$anonfun$apply$1$$anonfun$5.apply(RouterBuilderHelper.scala:66)
	at play.routing.RouterBuilderHelper$$anonfun$build$1$$anonfun$apply$1$$anonfun$5.apply(RouterBuilderHelper.scala:62)
	at play.api.mvc.Action$.invokeBlock(Action.scala:533)
	at play.api.mvc.Action$.invokeBlock(Action.scala:530)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ExceptionInInitializerError: null
	at io.skymind.skil.daemon.ProcessLauncherDaemon.lambda$runMain$1(ProcessLauncherDaemon.java:569)
	at io.skymind.auth.FunctionUtil$3.apply(FunctionUtil.java:128)
	at io.skymind.auth.FunctionUtil$3.apply(FunctionUtil.java:103)
	... 31 common frames omitted
Caused by: org.apache.shiro.config.ConfigurationException: java.io.FileNotFoundException: /tmp/shiro_temp.ini (No such file or directory)
	at org.apache.shiro.config.Ini.loadFromPath(Ini.java:242)
	at org.apache.shiro.config.Ini.fromResourcePath(Ini.java:225)
	at io.skymind.zeppelin.rest.ZeppelinRest.<clinit>(ZeppelinRest.java:28)
	... 34 common frames omitted
Caused by: java.io.FileNotFoundException: /tmp/shiro_temp.ini (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.apache.shiro.io.ResourceUtils.loadFromFile(ResourceUtils.java:149)
	at org.apache.shiro.io.ResourceUtils.getInputStreamForPath(ResourceUtils.java:135)
	at org.apache.shiro.config.Ini.loadFromPath(Ini.java:240)
	... 36 common frames omitted
09:21:09.098 [application-akka.actor.default-dispatcher-22] ERROR application - 

! @790kp44l5 - Internal server error, for (POST) [/rpc/a97f9b4d-4e83-47a7-ae65-0927c4b44c4d/api/notebook] ->
 
play.api.UnexpectedException: Unexpected exception[InvocationTargetException: null]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:277)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.routing.RouterBuilderHelper$$anonfun$build$1$$anonfun$apply$1$$anonfun$5.apply(RouterBuilderHelper.scala:66)
	at play.routing.RouterBuilderHelper$$anonfun$build$1$$anonfun$apply$1$$anonfun$5.apply(RouterBuilderHelper.scala:62)
	at play.api.mvc.Action$.invokeBlock(Action.scala:533)
	at play.api.mvc.Action$.invokeBlock(Action.scala:530)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	... 6 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at io.skymind.skil.daemon.ProcessLauncherDaemon.lambda$runMain$1(ProcessLauncherDaemon.java:569)
	at io.skymind.auth.FunctionUtil$3.apply(FunctionUtil.java:128)
	at io.skymind.auth.FunctionUtil$3.apply(FunctionUtil.java:103)
	... 31 common frames omitted
Caused by: org.apache.shiro.config.ConfigurationException: java.io.FileNotFoundException: /tmp/shiro_temp.ini (No such file or directory)
	at org.apache.shiro.config.Ini.loadFromPath(Ini.java:242)
	at org.apache.shiro.config.Ini.fromResourcePath(Ini.java:225)
	at io.skymind.zeppelin.rest.ZeppelinRest.<clinit>(ZeppelinRest.java:28)
	... 34 common frames omitted
Caused by: java.io.FileNotFoundException: /tmp/shiro_temp.ini (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.apache.shiro.io.ResourceUtils.loadFromFile(ResourceUtils.java:149)
	at org.apache.shiro.io.ResourceUtils.getInputStreamForPath(ResourceUtils.java:135)
	at org.apache.shiro.config.Ini.loadFromPath(Ini.java:240)
	... 36 common frames omitted

**Comment by wangfeng-skymind** [comment]
@wmeddie i should send the file /tmp/shiro_temp.ini to the customer,right?

**Comment by wmeddie** [comment]
Yes. And see If you can ask them to change the tmp cleaning settings to prevent that file from being deleted by adding a file: /etc/tmpfiles.d/skil_shiro.conf with the line x /tmp/shiro_temp.ini.

**Comment by ShamsUlAzeem** [comment]
@wmeddie status on this?

**Comment by wmeddie** [comment]
This was fixed.
